GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [1]

  | Name          | Type                  | Params | Mode
----------------------------------------------------------------
0 | gw_mod        | GWModule              | 6.3 M  | train
1 | selection_mod | SingleDomainSelection | 0      | train
2 | loss_mod      | GWLosses2Domains      | 6.3 M  | train
----------------------------------------------------------------
484 K     Trainable params
5.8 M     Non-trainable params
6.3 M     Total params
25.254    Total estimated model params size (MB)
43        Modules in train mode
35        Modules in eval mode
Sanity Checking DataLoader 0: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  6.23it/s]

Detected KeyboardInterrupt, attempting graceful shutdown ...
Exception in thread Thread-4 (_pin_memory_loop):
Traceback (most recent call last):
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/torch/utils/data/_utils/pin_memory.py", line 59, in _pin_memory_loop
    do_one_step()
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/torch/utils/data/_utils/pin_memory.py", line 35, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/torch/multiprocessing/reductions.py", line 541, in rebuild_storage_fd
    fd = df.detach()
         ^^^^^^^^^^^
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/multiprocessing/connection.py", line 519, in Client
    c = SocketClient(address)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/multiprocessing/connection.py", line 647, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f151ade3380>
Traceback (most recent call last):
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1604, in __del__
    self._shutdown_workers()
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1568, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/multiprocessing/popen_fork.py", line 40, in wait
    if not wait([self.sentinel], timeout):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/multiprocessing/connection.py", line 948, in wait
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/torch/utils/data/_utils/signal_handling.py", line 73, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1367186) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.
Exception ignored in atexit callback: <function _start_and_connect_service.<locals>.teardown_atexit at 0x7f1460f0b9c0>
Traceback (most recent call last):
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/lib/service_connection.py", line 94, in teardown_atexit
    conn.teardown(hooks.exit_code)
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/lib/service_connection.py", line 226, in teardown
    self._router.join()
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/interface/router.py", line 75, in join
    self._thread.join()
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/threading.py", line 1119, in join
    self._wait_for_tstate_lock()
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/threading.py", line 1139, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt:
